sudo: required

language: cpp

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - . ./DiligentCore/BuildTools/Scripts/travis/before_install.sh

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake

matrix:
  include:
  - os: linux
    compiler: gcc
    env:
      - CONFIG=Debug
  - os: osx
    compiler: clang
    env: 
      - CONFIG=Debug
      - IOS=false
  - os: osx
    compiler: clang
    env: 
      - CONFIG=Debug
      - IOS=true
  - os: linux
    compiler: gcc
    env:
      - CONFIG=Release
  - os: osx
    compiler: clang
    env: 
      - CONFIG=Release
      - IOS=false
  - os: osx
    compiler: clang
    env: 
      - CONFIG=Release
      - IOS=true

script:

  - . ./DiligentCore/BuildTools/Scripts/travis/build.sh "-DDILIGENT_ENABLE_TESTS=TRUE"
